# SSH agent
setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock
set -g update-environment -r

# Colors
set-option -g status-justify right
set-option -g status-bg colour233
set-option -g status-fg cyan
set-option -g status-interval 5
set-option -g status-left-length 30
set-option -g status-left ''
set-option -g status-right '#[default]'
set-option -g visual-activity on

set -g pane-border-style fg=cyan
set -g pane-active-border-style fg=cyan
set -g pane-active-border-style bg=default
