# argp
export ARGP_HELP_FMT="no-dup-args-note"

if [ "$INSIDE_EMACS" ]; then
    export TERM=dumb-emacs-ansi COLORTERM=1
    PROMPT_COMMAND=
    export PS1='[%n@%m]%~$ '
fi

# For Emacs Tramp
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

# git status
autoload -Uz vcs_info
precmd() { vcs_info 2>/dev/null }

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '%b'

export PS1='[%n@%m]%~$ '

# Right promp w/ git info
autoload -U colors && colors
RPROMPT=%{$fg[cyan]%}\$vcs_info_msg_0_%{$reset_color%}

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY

# jump
__jump_chpwd() {
  jump chdir
}

jump_completion() {
  reply="'$(jump hint "$@")'"
}

j() {
  local dir="$(jump cd $@)"
  test -d "$dir" && cd "$dir"
}

typeset -gaU chpwd_functions
chpwd_functions+=__jump_chpwd

compctl -U -K jump_completion j

autoload -Uz compinit
compinit
setopt COMPLETE_ALIASES
setopt PROMPT_SUBST
zstyle ':completion:*' rehash true

alias ls='ls --color=auto'
alias grep='grep --color=auto'

# oh-my-zsh
export ZSH=/usr/share/oh-my-zsh/

plugins=(
    command-time
    extract
    fd
    git
)

source $ZSH/oh-my-zsh.sh || true

# command-time min seconds
ZSH_COMMAND_TIME_MIN_SECONDS=300

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Additional keybindings
if [ -z "$INSIDE_EMACS" ]; then
    bindkey "^[[1;5C" forward-word
    bindkey "^[[1;5D" backward-word
fi

# Editor
export EDITOR="nano"

# Node.js
PATH="$HOME/.node_modules/bin:$PATH"
export npm_config_prefix=~/.node_modules

# Go
export GOROOT=/usr/lib/go
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# Python
export PATH=~/.local/bin:$PATH

# Rust
export PATH=~/.cargo/bin:$PATH

# Matlab
export PATH=$PATH:~/MATLAB/bin

# Parquet tools
export PATH=$PATH:/usr/share/java/parquet-tools/

# Spark
export PATH=$PATH:/opt/apache-spark/bin

# nvm
#unset npm_config_prefix
#export PATH=/home/ryanw/.nvm/versions/node/v16.4.0/bin/:$PATH
#source /usr/share/nvm/init-nvm.sh

# Completion
complete -W "--left-only --right-only" trim

# perl
export PATH=$PATH:~/perl5/bin
cpanm --local-lib=~/perl5 local::lib >/dev/null && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib) || true

# npm
npm config set prefix '~/.local' || true
export PATH=~/.local/bin:$PATH